### ISSUE TITLE
Update to 1.3.0?

### ISSUE THREAD

**Issue by jorbig** [bleakvin/hass-guacamole#3]
I love this addon! It's VERY helpful. But could you please update it from 1.2.0 to 1.3.0? Or else instruct us how to do this manually? Thanks in advance!

**Comment by jorbig** [comment]
Wow, you already updated it. Thanks so much! But when I try to install it in Hassio, I get this error message:


`404 Client Error for http+docker://localhost/v1.40/images/create?tag=1.3.0&fromImage=bleakvin%2Fhass-guacamole: Not Found ("manifest for bleakvin/hass-guacamole:1.3.0 not found: manifest unknown: manifest unknown")`

**Comment by bleakvin** [comment]
Yeah i had a quick look at it yesterday. I couldn't yet manage to tag the docker build correctly thats why you get that error message. I hope to get that going soon but I dont really know what I am doing here. 😅

**Comment by jorbig** [comment]
I see you fixed this already. It installs fine now, but the Web UI won't open (the browser displays a 502 Bad Gateway error). If it helps, this is what the log says:

`/init: 11: /init: /bin/importas: Exec format error
/etc/s6/init/init-stage1: 7: /etc/s6/init/init-stage1: importas: Exec format error
/etc/s6/init/init-stage1: 8: /etc/s6/init/init-stage1: define: Exec format error
/etc/s6/init/init-stage1: 17: /etc/s6/init/init-stage1: Syntax error: "}" unexpected (expecting "then")`

**Comment by bleakvin** [comment]
Should be fixed now. You might have to reinstall the Add-on. Create a partial Snapshot and restore it after reinstalling.

**Comment by jorbig** [comment]
Nope, I removed it, installed it again, but still the same 502 Bad Gateway error when trying to reach the Web UI.....

**Comment by jorbig** [comment]
You're right! It works fine now, thanks a bunch!!

Op do 27 mei 2021 om 16:02 schreef bleakvin ***@***.***>:

**Comment by bleakvin** [comment]
Perfect! Closing this.
